### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by SeanAhB** [michaellee8/tkpss-table-tennis-club#1]
1. 每個post 加返個名比大家見到
    同一d資料比人見到例如幾時post果d
2. Edit post + del post
3. 每個post可以留言
4. 可以post d 文件？ 短片？

**Comment by michaellee8** [comment]
1. 係本身有ui但係未implement logic
2. Del 係本身有ui，但係edit個個無
3. 同1
4. 文件、短片、圖片都好大空間，係呢到要store好快就會過咗免費容量，但係可以放個睇facebook page 嘅 框框喺度

Btw, it is Better to use English here.

**Comment by SeanAhB** [comment]
Give up edit function
Maybe the doc/video upload function can be less priority

**Comment by michaellee8** [comment]
Nice, 1, **the delete part** of 2 and 3 will be on v1.0

**Comment by michaellee8** [comment]
Resolved in recent comment, please review
