### ISSUE TITLE
個人檔案/profile page

### ISSUE THREAD

**Issue by SeanAhB** [michaellee8/tkpss-table-tennis-club#2]
1. 加個stone no.
2. 加個lv.
3. 加班 名 學號 
4. 只你自己見到自個d能力值 其他人見唔到 除左lv.可以比人睇

**Comment by michaellee8** [comment]
1. It is quite possible and do you think displaying an bunch of stone images will be better than just a number? I believe we have to discuss the range of number of stones.
2. It can be easily implemented
3. as 2
4. It is possible, but i believe it will not be on the top of task list so far.
